/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AppLayoutRouteImport } from './routes/_app-layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupUniversityRouteImport } from './routes/signup/university'
import { Route as SignupAccountRouteImport } from './routes/signup/account'
import { Route as AppLayoutEventsRouteImport } from './routes/_app-layout/events'
import { Route as AppLayoutClubsRouteImport } from './routes/_app-layout/clubs'
import { Route as AppLayoutCalendarRouteImport } from './routes/_app-layout/calendar'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupUniversityRoute = SignupUniversityRouteImport.update({
  id: '/signup/university',
  path: '/signup/university',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupAccountRoute = SignupAccountRouteImport.update({
  id: '/signup/account',
  path: '/signup/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutEventsRoute = AppLayoutEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutClubsRoute = AppLayoutClubsRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutCalendarRoute = AppLayoutCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/calendar': typeof AppLayoutCalendarRoute
  '/clubs': typeof AppLayoutClubsRoute
  '/events': typeof AppLayoutEventsRoute
  '/signup/account': typeof SignupAccountRoute
  '/signup/university': typeof SignupUniversityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/calendar': typeof AppLayoutCalendarRoute
  '/clubs': typeof AppLayoutClubsRoute
  '/events': typeof AppLayoutEventsRoute
  '/signup/account': typeof SignupAccountRoute
  '/signup/university': typeof SignupUniversityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app-layout': typeof AppLayoutRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/_app-layout/calendar': typeof AppLayoutCalendarRoute
  '/_app-layout/clubs': typeof AppLayoutClubsRoute
  '/_app-layout/events': typeof AppLayoutEventsRoute
  '/signup/account': typeof SignupAccountRoute
  '/signup/university': typeof SignupUniversityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/calendar'
    | '/clubs'
    | '/events'
    | '/signup/account'
    | '/signup/university'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/calendar'
    | '/clubs'
    | '/events'
    | '/signup/account'
    | '/signup/university'
  id:
    | '__root__'
    | '/'
    | '/_app-layout'
    | '/dashboard'
    | '/login'
    | '/_app-layout/calendar'
    | '/_app-layout/clubs'
    | '/_app-layout/events'
    | '/signup/account'
    | '/signup/university'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SignupAccountRoute: typeof SignupAccountRoute
  SignupUniversityRoute: typeof SignupUniversityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app-layout': {
      id: '/_app-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/university': {
      id: '/signup/university'
      path: '/signup/university'
      fullPath: '/signup/university'
      preLoaderRoute: typeof SignupUniversityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/account': {
      id: '/signup/account'
      path: '/signup/account'
      fullPath: '/signup/account'
      preLoaderRoute: typeof SignupAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app-layout/events': {
      id: '/_app-layout/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AppLayoutEventsRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app-layout/clubs': {
      id: '/_app-layout/clubs'
      path: '/clubs'
      fullPath: '/clubs'
      preLoaderRoute: typeof AppLayoutClubsRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app-layout/calendar': {
      id: '/_app-layout/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppLayoutCalendarRouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface AppLayoutRouteChildren {
  AppLayoutCalendarRoute: typeof AppLayoutCalendarRoute
  AppLayoutClubsRoute: typeof AppLayoutClubsRoute
  AppLayoutEventsRoute: typeof AppLayoutEventsRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppLayoutCalendarRoute: AppLayoutCalendarRoute,
  AppLayoutClubsRoute: AppLayoutClubsRoute,
  AppLayoutEventsRoute: AppLayoutEventsRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppLayoutRoute: AppLayoutRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SignupAccountRoute: SignupAccountRoute,
  SignupUniversityRoute: SignupUniversityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
